import { Template } from './types';

/**
 * Turn (template + chosen params) into the final JS string that gets written
 * into the native JS code slot (`stepParams.jsSettings.runJs.code`).
 *
 * We inject the params as a single `const $p = {...}` prefix rather than doing
 * `{{mustache}}` substitution inside the body — string interpolation breaks on
 * quotes/newlines, while a JSON-serialized object is always valid and the body
 * just reads `$p.fieldName`.
 */
/** djb2 — fingerprint of the generated code, stored alongside the template
 *  config so we can detect manual edits to the JS (drift) on reconfigure */
export function hashCode(s: string): number {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) | 0;
  return h;
}

export function generateCode(template: Template, params: Record<string, any>): string {
  // free-form templates: the user's code IS the final code
  if (template.rawCode) {
    return String(params?.code ?? '');
  }
  const json = JSON.stringify(params ?? {}, null, 2);
  return [
    `// ⚙️ Generated by JS Template Library — template "${template.key}".`,
    `// Re-open "Template settings" (gear menu) to reconfigure.`,
    `// Manual edits below are overwritten the next time you reconfigure.`,
    `const $p = ${json};`,
    '',
    template.body.trim(),
    '',
  ].join('\n');
}
